### ISSUE TITLE
keyboard commands are global

### ISSUE THREAD

**Issue by briandela** [nearform/deck-app#60]
Open deck, switch to another app, hit cmd+ctrl+p and it will switch back to electron and start producing the pdf.

**Comment by davidmarkclements** [comment]
yes - thats a design choice

when you're in a presentation environment the system should act differently

is cmd + ctrl + p clashing with a shortcut for another critical app used for presentations?

**Comment by briandela** [comment]
Sublime. It's actually cmd+b for build in sublime (when running examples etc) 

Brian

**Comment by davidmarkclements** [comment]
what about ctrl + cmd + b
